openapi: 3.1.0
info:
  title: Schemas of `nodes._common` Category
  description: Schemas of `nodes._common` category.
  version: 1.0.0
paths: {}
components:
  schemas:
    NodesResponseBase:
      description: Provides base response structure for node-related operations.
      type: object
      properties:
        _nodes:
          description: Contains statistics about the number of nodes selected by the request's node filters.
          $ref: '_common.yaml#/components/schemas/NodeStatistics'

    SampleType:
      type: string
      description: The type of resource to sample.
      oneOf:
        - description: Samples block I/O operations.
          const: block
        - description: Samples CPU utilization.
          const: cpu
        - description: Samples process wait times.
          const: wait
